# Generated by Django 4.2.1 on 2023-09-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuntes',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
